name: Hola Mundo Workflow

on:
  push:
    branches:
    #La branches es por tanto una lista de todas las ramas que estará escuchando el yml
      - main
      - newBranch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:  
      #- name: Checkout code
      #  uses: actions/checkout@v2
      - name: Clonar repo
        uses: actions/checkout@v2
      - name: Run Hello World Script
        run: echo "hola mundo"
      - name: Cat hola-mundo.txt
        run: cat hola-mundo.txt
      